/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GitWorkflowTest.app;

import GitWorkflowTest.list.LinkedList;

import static GitWorkflowTest.utilities.StringUtils.join;
import static GitWorkflowTest.utilities.StringUtils.split;
import static GitWorkflowTest.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) { //masterd
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
