/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GitWorkflowTest.app;

class MessageUtils {
    public static String getMessage() {
        return "Hello aaaa     World!";
    }
}
