name: BatchTest

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Read all repos
        run: |
          jq -r .modules[].name ./.github/workflows/repositories.json > /tmp/repos.json
          cat /tmp/repos.json
      - name: Collect all packages
        run: |
          key=""
          x="true"
          while ("$x" != "false");do key=$(jq -r .data.repository.packages.pageInfo.endCursor /tmp/response.json);curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query":"query{repository(name:\"ballerina-lang\",owner:\"ballerina-platform\"){packages(first:100,orderBy:{field:CREATED_AT,direction:ASC}, after:\"'$key'\"){nodes{id,name},pageInfo{endCursor,hasNextPage}}}}"}' --url 'https://api.github.com/graphql' -o /tmp/response.json;jq -r .data.repository.packages.nodes[].name /tmp/response.json >> /tmp/packages.json;x=$(jq -r .data.repository.packages.pageInfo.hasNextPage /tmp/response.json);done;
      - name: Collect package versions
        run: |
          cat tmp/packages.json
