name: DeleteAllUnusedPackages

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Read access list
        run: "cat ./.github/workflows/package_delete_usernames.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username' > /tmp/auth-user.json"
      - name: Set authorized username
        id: setUname
        run: printf "::set-output name=foundUname::%s" $(cat /tmp/auth-user.json)
      - name: Read all repos
        if: steps.setUname.outputs.foundUname != ''
        run: |
          jq -r .modules[].name ./.github/workflows/repositories.json > /tmp/repos.json
      - name: Collect all packages
        if: steps.setUname.outputs.foundUname != ''
        run: |
          "./.github/workflows/delete-packages.sh"