# This is a basic workflow to help you get started with Actions

name: DeletePackages

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: update_check_run
        with:
          route: DELETE /user/packages/maven/{package_name}
          package_name: GitWorkflowTestv6.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

