# This is a basic workflow to help you get started with Actions

name: DeletePackages

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Get package version ids
        run: |
          curl -H "Authorization: bearer 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" -X POST -d '{"query":"query{repository(name:\"GitWorkflowTest\",owner:\"dilanSachi\"){packages(last:10){edges{node{id,name,versions(first:10){edges{node{id}}}}}}}}"}' --url https://api.github.com/graphql -o /tmp/response.json
      - name: Display data
        run: "cat /tmp/response.json"
