# This is a basic workflow to help you get started with Actions

name: DeletePackages

# Controls when the action will run. 
on: 
  workflow_dispatch:
      inputs:
        owner:
          description: 'Repo Owner'     
          required: true
          default: 'dilanSachi'
        repo:
          description: 'Repository'     
          required: true
          default: 'GitWorkflowTest'
        package:
          description: 'Specific package'
          required: true
        version:
          description: 'Package version'
          required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Get package version ids
        run: |
          curl -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" -X POST -d '{"query":"query{repository(name:\"GitWorkflowTest\",owner:\"dilanSachi\"){packages(last:10){edges{node{id,name,versions(first:10){edges{node{id,version}}}}}}}}"}' --url https://api.github.com/graphql -o /tmp/response.json
      - name: Display data
        run: "cat /tmp/response.json"
      - name: Filter Packages
        run: "cat /tmp/response.json | jq -r '.data.repository.packages.edges[] | select(.node.name==\"${{ github.event.inputs.package }}\")|.node.versions.edges[]|select(.node.version==\"${{ github.event.inputs.version }}\")|.node.id' > /tmp/release.json"
      - name: Show Selected Package
        id: release
        run: "cat /tmp/release.json"
      - name: print
        run: printf "::set-output name=id::%s" $(cat /tmp/release.json)
      - name: show in screen
        run: "echo ${{steps.release.outputs.id}}"
#       - name: Delete Selected Package
#         uses: actions/delete-package-versions@v1.0.3
# #         if: steps.release.outputs.id != ''
#         with:
#           package-version-ids: MDE0OlBhY2thZ2VWZXJzaW9uODUxNDE1Mw==
