name: Create Automated Summary PR
on:
  push:
    branches:
      - 'nightly-**'
    paths:
      - 'app/src/**/App.java'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create pull request for new summary
        run: gh pr create --title "[Automated] Update summary csv files" --body "Update summary csv files"
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
