name: testbuild

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: 11
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.GITHUB_TOKEN }}
          ACTOR_SECRET: ${{secrets.GITHUB_ACTOR}}
        run: |
          echo "$SUPER_SECRET"|
          echo "$ACTOR_SECRET"
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}