name: Test

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Show Username
        run: echo ${{github.actor}}
      - name: test
        run: "cat ./.github/workflows/UserWithPackageDeletionAccess.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username' > /tmp/auth-user.json"
#      - name: Read access list
#        id: setUname
#        run: printf "::set-output name:foundUname" $("cat ./.github/workflows/UserWithPackageDeletionAccess.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username'")
      - name: Read access list
        id: setUname
        run: printf "::set-output name=foundUname::%s" $(cat /tmp/auth-user.json)
      - name: Print found uname
        run: "echo ${{steps.setUname.outputs.foundUname}}"
#      - name: Delete Selected Package
#        uses: actions/delete-package-versions@v1.0.3
#        if: steps.setid.outputs.id != ''
#        with:
#          package-version-ids: ${{ steps.setid.outputs.id }}
#          token: ${{ secrets.GIT_PAT }}
