name: Test

# Controls when the action will run. 
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Show Username
        run: echo ${{github.actor}}
      - name: Read access list
        id: setUname
        run: printf "::set-output name:foundUname" $("cat ./UserWithPackageDeletionAccess.json | jq -r '.usernames[]|select(.username==\"${{github.actor}}\").username'")
      - name: Print found uname
        run: "echo ${{steps.setUname.outputs.foundUname}}"